kotlin.code.style=official
android.useAndroidX=true
org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC

LIBRARY_VERSION=0.1.22
GROUP=meg.listshop.bff
# org.gradle.configuration-cache=true No config cache with maven... https://github.com/touchlab/KMMBridge/issues/272

# Enable parallel task execution across modules
org.gradle.parallel=true

# Enable the build cache to reuse previous results
org.gradle.caching=true


