# Publish Android artifacts to GitHub Packages on release.
name: Android-Publish
on:
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish Android Release and Debug
        run: |
          ./gradlew publishAllPublicationsToGitHubPackagesRepository \
           -PNATIVE_BUILD_TYPE=DEBUG \
            -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -PGITHUB_REPO=${{ github.repository }} \
            -PENABLE_PUBLISHING=true \
            --no-daemon --info --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
