# Publish a build for release.
name: KMMBridge-Release
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  call-publish:
    uses: ./.github/workflows/Base-Publish.yml
    with:
      build-debug: false
      publish-tasks: kmmBridgePublish
